apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
  labels:
    app: redis-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-replica
  template:
    metadata:
      labels:
        app: redis-replica
    spec:
      containers:
        - name: redis
          image: redis:latest
          command: ["redis-server", "--replicaof", "10.104.245.182", "6379"]
          ports:
            - containerPort: 6379
